//
//  GlobalValuesWorker.swift
//  MarketCoins
//
//  Created by Juliano Sgarbossa on 28/04/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GlobalValuesWorker {
    
    private let dataProvider: GlobalValuesDataProvider?
    private var completion: ((Result<GlobalModel?, CryptocurrenciesError>) -> Void)?
    
    init(dataProvider: GlobalValuesDataProvider = GlobalValuesDataProvider()) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFetchGlobalValues(completion: @escaping ((Result<GlobalModel?, CryptocurrenciesError>) -> Void)) {
        dataProvider?.fetchGlobalValues()
        self.completion = completion
    }
}

extension GlobalValuesWorker: GlobalValuesDataProviderDelegate {
    func sucess(model: Any) {
        guard let completion = self.completion else {
            fatalError("Completion not implemented!")
        }
        completion(.success(model as? GlobalModel))
    }
    
    func errorData(_ provider: (any GenericDataProviderDelegate)?, error: any Error) {
        guard let completion = self.completion else {
            fatalError("Completion not implemented!")
        }
        
        if error.errorCode == 500 {
            completion(.failure(.internalServerError))
        } else if error.errorCode == 400 {
            completion(.failure(.badRequestError))
        } else if error.errorCode == 404 {
            completion(.failure(.notFoundError))
        } else {
            completion(.failure(.undefinedError))
        }
    }
}
