//
//  MarketChartDataWorker.swift
//  MarketCoins
//
//  Created by Juliano Sgarbossa on 14/05/25.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MarketChartDataWorker {
    
    private let dataProvider: MarketChartDataProvider?
    private var completion: ((Result<MarketChartModel?, CryptocurrenciesError>) -> Void)?
    
    init(dataProvider: MarketChartDataProvider = MarketChartDataProvider()) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFetchMarketChart(id: String,
                            baseCoin: String,
                            from: String,
                            to: String,
                            completion: @escaping ((Result<MarketChartModel?, CryptocurrenciesError>) -> Void)) {
        dataProvider?.fetchMarketChartRange(id: id, currency: baseCoin, from: from, to: to)
        self.completion = completion
    }
}

extension MarketChartDataWorker: MarketChartDataProviderDelegate {
   
    func sucess(model: Any) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        
        completion(.success(model as? MarketChartModel))
    }
    
    func errorData(_ provider: (any GenericDataProviderDelegate)?, error: any Error) {
        guard let completion = self.completion else {
            fatalError("Completion not implemented!")
        }
        
        if error.errorCode == 500 {
            completion(.failure(.internalServerError))
        } else if error.errorCode == 400 {
            completion(.failure(.badRequestError))
        } else if error.errorCode == 404 {
            completion(.failure(.notFoundError))
        } else {
            completion(.failure(.undefinedError))
        }
    }
}
